export default function Terms() {
  return (
    <div style={{ padding: 40, maxWidth: 800, margin: "0 auto", lineHeight: 1.7 }}>

      <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 20 }}>
        Terms of Service
      </h1>

      <p style={{ marginBottom: 20, color: "#666" }}>
        Last updated: 2026-03
      </p>

      <h2>1. Overview</h2>
      <p>
        Welcome to SayNo AI. By using this website, you agree to these terms.
        If you do not agree, please do not use the service.
      </p>

      <h2>2. Use of Service</h2>
      <p>
        SayNo AI provides AI-generated responses for entertainment and general use.
        You agree not to misuse the service or use it for illegal or harmful purposes.
      </p>

      <h2>3. AI-Generated Content</h2>
      <p>
        Responses are generated by artificial intelligence and may not always be accurate,
        appropriate, or reliable. Use them at your own discretion.
      </p>

      <h2>4. No Liability</h2>
      <p>
        We are not responsible for any outcomes resulting from the use of generated content.
        You are solely responsible for how you use the responses.
      </p>

      <h2>5. Availability</h2>
      <p>
        We may modify, suspend, or discontinue the service at any time without notice.
      </p>

      <h2>6. Intellectual Property</h2>
      <p>
        The website design and branding belong to SayNo AI. You may use generated
        responses freely for personal use.
      </p>

      <h2>7. Changes to Terms</h2>
      <p>
        We may update these terms from time to time. Continued use of the service
        means you accept the updated terms.
      </p>

      <h2>8. Contact</h2>
      <p>
        If you have any questions, feel free to contact us.
      </p>

    </div>
  );
}